/*
insert license info here
*/
using System;

namespace DataAccess.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class DbBackupSet
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private long _id; 
		private string _cycle; 
		private string _daytime; 
		private string _weekday; 
		private string _weektime; 
		private long _monthday; 
		private string _monthtime; 
		private string _createuser; 
		private DateTime _createtime; 
		private string _upduser; 
		private DateTime _updtime; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public DbBackupSet()
		{
			_id = 0; 
			_cycle = null; 
			_daytime = null; 
			_weekday = null; 
			_weektime = null; 
			_monthday = 0; 
			_monthtime = null; 
			_createuser = null; 
			_createtime = new DateTime(); 
			_upduser = null; 
			_updtime = new DateTime(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Cycle
		{
			get { return _cycle; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for Cycle", value, value.ToString());
				
				_isChanged |= (_cycle != value); _cycle = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string DayTime
		{
			get { return _daytime; }
			set	
			{
				if( value!= null && value.Length > 10)
					throw new ArgumentOutOfRangeException("Invalid value for DayTime", value, value.ToString());
				
				_isChanged |= (_daytime != value); _daytime = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string WeekDay
		{
			get { return _weekday; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for WeekDay", value, value.ToString());
				
				_isChanged |= (_weekday != value); _weekday = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string WeekTime
		{
			get { return _weektime; }
			set	
			{
				if( value!= null && value.Length > 10)
					throw new ArgumentOutOfRangeException("Invalid value for WeekTime", value, value.ToString());
				
				_isChanged |= (_weektime != value); _weektime = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public long MonthDay
		{
			get { return _monthday; }
			set { _isChanged |= (_monthday != value); _monthday = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string MonthTime
		{
			get { return _monthtime; }
			set	
			{
				if( value!= null && value.Length > 10)
					throw new ArgumentOutOfRangeException("Invalid value for MonthTime", value, value.ToString());
				
				_isChanged |= (_monthtime != value); _monthtime = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUser
		{
			get { return _createuser; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for CreateUser", value, value.ToString());
				
				_isChanged |= (_createuser != value); _createuser = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateTime
		{
			get { return _createtime; }
			set { _isChanged |= (_createtime != value); _createtime = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string UpdUser
		{
			get { return _upduser; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for UpdUser", value, value.ToString());
				
				_isChanged |= (_upduser != value); _upduser = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime UpdTime
		{
			get { return _updtime; }
			set { _isChanged |= (_updtime != value); _updtime = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
