/*
insert license info here
*/
using System;

namespace DataAccess.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class IncomingCallSet
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private long _id; 
		private long _isenable; 
		private long _isallowshutdown; 
		private string _callmodel; 
		private string _devicetype; 
		private string _callport; 
		private string _baudrate; 
		private string _createuser; 
		private DateTime _createtime; 
		private string _upduser; 
		private DateTime _updtime; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public IncomingCallSet()
		{
			_id = 0; 
			_isenable = 0; 
			_isallowshutdown = 0; 
			_callmodel = null; 
			_devicetype = null; 
			_callport = null; 
			_baudrate = null; 
			_createuser = null; 
			_createtime = new DateTime(); 
			_upduser = null; 
			_updtime = new DateTime(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public long IsEnable
		{
			get { return _isenable; }
			set { _isChanged |= (_isenable != value); _isenable = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public long IsAllowShutDown
		{
			get { return _isallowshutdown; }
			set { _isChanged |= (_isallowshutdown != value); _isallowshutdown = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CallModel
		{
			get { return _callmodel; }
			set	
			{
				if( value!= null && value.Length > 20)
					throw new ArgumentOutOfRangeException("Invalid value for CallModel", value, value.ToString());
				
				_isChanged |= (_callmodel != value); _callmodel = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string DeviceType
		{
			get { return _devicetype; }
			set	
			{
				if( value!= null && value.Length > 10)
					throw new ArgumentOutOfRangeException("Invalid value for DeviceType", value, value.ToString());
				
				_isChanged |= (_devicetype != value); _devicetype = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CallPort
		{
			get { return _callport; }
			set	
			{
				if( value!= null && value.Length > 10)
					throw new ArgumentOutOfRangeException("Invalid value for CallPort", value, value.ToString());
				
				_isChanged |= (_callport != value); _callport = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string BaudRate
		{
			get { return _baudrate; }
			set	
			{
				if( value!= null && value.Length > 10)
					throw new ArgumentOutOfRangeException("Invalid value for BaudRate", value, value.ToString());
				
				_isChanged |= (_baudrate != value); _baudrate = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUser
		{
			get { return _createuser; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for CreateUser", value, value.ToString());
				
				_isChanged |= (_createuser != value); _createuser = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateTime
		{
			get { return _createtime; }
			set { _isChanged |= (_createtime != value); _createtime = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string UpdUser
		{
			get { return _upduser; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for UpdUser", value, value.ToString());
				
				_isChanged |= (_upduser != value); _upduser = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime UpdTime
		{
			get { return _updtime; }
			set { _isChanged |= (_updtime != value); _updtime = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
