/*
insert license info here
*/
using System;

namespace DataAccess.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class OrdersDiscountManage
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private long _id; 
		private string _discounttype; 
		private string _discountstyle; 
		private string _ordersno; 
		private string _menuno; 
		private string _discountruleno; 
		private float _discountpercent; 
		private float _discountmoney; 
		private string _createuser; 
		private DateTime _createtime; 
		private string _upduser; 
		private DateTime _updtime; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public OrdersDiscountManage()
		{
			_id = 0; 
			_discounttype = null; 
			_discountstyle = null; 
			_ordersno = null; 
			_menuno = null; 
			_discountruleno = null; 
			_discountpercent = 0; 
			_discountmoney = 0; 
			_createuser = null; 
			_createtime = new DateTime(); 
			_upduser = null; 
			_updtime = new DateTime(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string DiscountType
		{
			get { return _discounttype; }
			set	
			{
				if( value!= null && value.Length > 10)
					throw new ArgumentOutOfRangeException("Invalid value for DiscountType", value, value.ToString());
				
				_isChanged |= (_discounttype != value); _discounttype = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string DiscountStyle
		{
			get { return _discountstyle; }
			set	
			{
				if( value!= null && value.Length > 10)
					throw new ArgumentOutOfRangeException("Invalid value for DiscountStyle", value, value.ToString());
				
				_isChanged |= (_discountstyle != value); _discountstyle = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string OrdersNo
		{
			get { return _ordersno; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for OrdersNo", value, value.ToString());
				
				_isChanged |= (_ordersno != value); _ordersno = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string MenuNo
		{
			get { return _menuno; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for MenuNo", value, value.ToString());
				
				_isChanged |= (_menuno != value); _menuno = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string DiscountRuleNo
		{
			get { return _discountruleno; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for DiscountRuleNo", value, value.ToString());
				
				_isChanged |= (_discountruleno != value); _discountruleno = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public float DiscountPercent
		{
			get { return _discountpercent; }
			set { _isChanged |= (_discountpercent != value); _discountpercent = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public float DiscountMoney
		{
			get { return _discountmoney; }
			set { _isChanged |= (_discountmoney != value); _discountmoney = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUser
		{
			get { return _createuser; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for CreateUser", value, value.ToString());
				
				_isChanged |= (_createuser != value); _createuser = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateTime
		{
			get { return _createtime; }
			set { _isChanged |= (_createtime != value); _createtime = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string UpdUser
		{
			get { return _upduser; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for UpdUser", value, value.ToString());
				
				_isChanged |= (_upduser != value); _upduser = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime UpdTime
		{
			get { return _updtime; }
			set { _isChanged |= (_updtime != value); _updtime = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
