/*
insert license info here
*/
using System;
using Microsoft.Practices.Prism.ViewModel;

namespace DataAccess.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class PrintPlanManage : NotificationObject
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private long _id; 
		private string _planno; 
		private string _planname; 
		private long _isenable; 
		private long _printcount; 
		private string _ordertype; 
		private string _printer; 
		private string _printmenu; 
		private string _printarea; 
		private string _createuser; 
		private DateTime _createtime; 
		private string _upduser; 
		private DateTime _updtime; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PrintPlanManage()
		{
			_id = 0; 
			_planno = null; 
			_planname = null; 
			_isenable = 0; 
			_printcount = 0; 
			_ordertype = null; 
			_printer = null; 
			_printmenu = null; 
			_printarea = null; 
			_createuser = null; 
			_createtime = new DateTime(); 
			_upduser = null; 
			_updtime = new DateTime(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public long Id
		{
			get { return _id; }
            set { _isChanged |= (_id != value); _id = value; RaisePropertyChanged("Id"); }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string PlanNo
		{
			get { return _planno; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for PlanNo", value, value.ToString());

                _isChanged |= (_planno != value); _planno = value; RaisePropertyChanged("PlanNo");
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string PlanName
		{
			get { return _planname; }
			set	
			{
				if( value!= null && value.Length > 20)
					throw new ArgumentOutOfRangeException("Invalid value for PlanName", value, value.ToString());

                _isChanged |= (_planname != value); _planname = value; RaisePropertyChanged("PlanName");
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public long IsEnable
		{
			get { return _isenable; }
            set { _isChanged |= (_isenable != value); _isenable = value; RaisePropertyChanged("IsEnable"); }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public long PrintCount
		{
			get { return _printcount; }
            set { _isChanged |= (_printcount != value); _printcount = value; RaisePropertyChanged("PrintCount"); }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string OrderType
		{
			get { return _ordertype; }
			set	
			{
				if( value!= null && value.Length > 20)
					throw new ArgumentOutOfRangeException("Invalid value for OrderType", value, value.ToString());

                _isChanged |= (_ordertype != value); _ordertype = value; RaisePropertyChanged("OrderType");
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Printer
		{
			get { return _printer; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for Printer", value, value.ToString());

                _isChanged |= (_printer != value); _printer = value; RaisePropertyChanged("Printer");
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string PrintMenu
		{
			get { return _printmenu; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for PrintMenu", value, value.ToString());

                _isChanged |= (_printmenu != value); _printmenu = value; RaisePropertyChanged("PrintMenu");
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string PrintArea
		{
			get { return _printarea; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for PrintArea", value, value.ToString());

                _isChanged |= (_printarea != value); _printarea = value; RaisePropertyChanged("PrintArea");
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUser
		{
			get { return _createuser; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for CreateUser", value, value.ToString());

                _isChanged |= (_createuser != value); _createuser = value; RaisePropertyChanged("CreateUser");
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateTime
		{
			get { return _createtime; }
            set { _isChanged |= (_createtime != value); _createtime = value; RaisePropertyChanged("CreateTime"); }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string UpdUser
		{
			get { return _upduser; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for UpdUser", value, value.ToString());

                _isChanged |= (_upduser != value); _upduser = value; RaisePropertyChanged("UpdUser");
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime UpdTime
		{
			get { return _updtime; }
            set { _isChanged |= (_updtime != value); _updtime = value; RaisePropertyChanged("UpdTime"); }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
