/*
insert license info here
*/
using System;

namespace DataAccess.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class UserPower
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private long _id; 
		private string _userno; 
		private string _departmentno; 
		private string _moduleno; 
		private long _isvalidate; 
		private long _canadd; 
		private long _canupd; 
		private long _candel; 
		private long _canselect; 
		private string _createuser; 
		private DateTime _createtime; 
		private string _upduser; 
		private DateTime _updtime; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public UserPower()
		{
			_id = 0; 
			_userno = null; 
			_departmentno = null; 
			_moduleno = null; 
			_isvalidate = 0; 
			_canadd = 0; 
			_canupd = 0; 
			_candel = 0; 
			_canselect = 0; 
			_createuser = null; 
			_createtime = new DateTime(); 
			_upduser = null; 
			_updtime = new DateTime(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string UserNo
		{
			get { return _userno; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for UserNo", value, value.ToString());
				
				_isChanged |= (_userno != value); _userno = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string DepartmentNo
		{
			get { return _departmentno; }
			set	
			{
				if( value!= null && value.Length > 20)
					throw new ArgumentOutOfRangeException("Invalid value for DepartmentNo", value, value.ToString());
				
				_isChanged |= (_departmentno != value); _departmentno = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string ModuleNo
		{
			get { return _moduleno; }
			set	
			{
				if( value!= null && value.Length > 10)
					throw new ArgumentOutOfRangeException("Invalid value for ModuleNo", value, value.ToString());
				
				_isChanged |= (_moduleno != value); _moduleno = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public long IsValidate
		{
			get { return _isvalidate; }
			set { _isChanged |= (_isvalidate != value); _isvalidate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public long CanAdd
		{
			get { return _canadd; }
			set { _isChanged |= (_canadd != value); _canadd = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public long CanUpd
		{
			get { return _canupd; }
			set { _isChanged |= (_canupd != value); _canupd = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public long CanDel
		{
			get { return _candel; }
			set { _isChanged |= (_candel != value); _candel = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public long CanSelect
		{
			get { return _canselect; }
			set { _isChanged |= (_canselect != value); _canselect = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUser
		{
			get { return _createuser; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for CreateUser", value, value.ToString());
				
				_isChanged |= (_createuser != value); _createuser = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateTime
		{
			get { return _createtime; }
			set { _isChanged |= (_createtime != value); _createtime = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string UpdUser
		{
			get { return _upduser; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for UpdUser", value, value.ToString());
				
				_isChanged |= (_upduser != value); _upduser = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime UpdTime
		{
			get { return _updtime; }
			set { _isChanged |= (_updtime != value); _updtime = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
